#!/bin/zsh

echo "Removing stopped containers"
docker rm $(docker ps -a | awk '{print $1}' | tail -n +2)
echo "Removing untagged images"
# docker images -q --filter "dangling=true" | xargs docker rmi
docker rmi $(docker images | grep "^<none>" | awk '{print $3}')