#!/bin/zsh
for i in `find . -name ".git" -type d -depth 2`; do
    r=`dirname $i`
    echo "\x1b[31m>>>>>>> Updating $r <<<<<<<<\x1b[0m"
    (cd $r; git-up)
    echo "\x1b[32m<<<<<<<<<< DONE >>>>>>>>>\x1b[0m"
done
