# Mac OS X uses path_helper to preload PATH, clear it out first
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

PATH=$PATH:/usr/local/opt/go/libexec/bin
PATH=$PATH:$(go env GOPATH)/bin
PATH=$PATH:"${HOME}/Library/Application Support/Coursier/bin"

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
# if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

if which jenv > /dev/null; then
    PATH="$HOME/.jenv/bin:$PATH"
    eval "$(jenv init -)"
fi

export PATH
