# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


#
# User configuration sourced by interactive shells
#
zmodload zsh/zprof
if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    source ~/.zplug/init.zsh && zplug update --self
fi

export ZSH_DOTENV_PROMPT=false

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv time)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=black,bold"
ZLE_RPROMPT_INDENT=0
# Essential
source ~/.zplug/init.zsh

zplug "lib/completion", from:oh-my-zsh
zplug "plugins/dotenv", from:oh-my-zsh
zplug "modules/git", from:prezto
zplug "modules/directory", from:prezto
zplug 'modules/osx', from:prezto
zplug 'modules/editor', from:prezto
zplug 'modules/terminal', from:prezto
zplug 'modules/history', from:prezto
zplug "modules/tmux", from:prezto
# zplug "nnao45/zsh-kubectl-completion"

zplug "zsh-users/zsh-completions",              defer:0
zplug "zsh-users/zsh-autosuggestions",          defer:2, on:"zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting",      defer:3, on:"zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-history-substring-search", defer:3, on:"zsh-users/zsh-syntax-highlighting"

zplug romkatv/powerlevel10k, as:theme, depth:1
# zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme

zplug "~/src/hierynomus/dotmac/zplug", from:local, defer:2

zstyle ':prezto:module:editor' dot-expansion 'yes'
zstyle ':prezto:*:*' case-sensitive 'no'
zstyle ':prezto:module:terminal' auto-title 'yes'
# zstyle ':completion:*:*:kubectl:*' list-grouped false

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

zplug load

[ -s "$HOME/.scm_breeze/scm_breeze.sh" ] && source "$HOME/.scm_breeze/scm_breeze.sh"

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

#eval "$(starship init zsh)"
if which scmpuff > /dev/null; then eval "$(scmpuff init -s)"; fi
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)

[[ -f ~/.secrets/zsh ]] && source ~/.secrets.zsh
